# Site settings
title: 点对点的SNS
SEOTitle: PDU:一种点对点的社交网络 | Peer-to-Peer Social Network | pdu.pub
email: hello@pdu.pub
description: "Parallel Digital Universe - A Peer-to-Peer Social Network"
keyword: "p2p, sns, social network, pdu"
url: "https://pdu.pub"
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
theme: jekyll-theme-architect



# Sidebar settings
sidebar: true
sidebar-about-description: Email: <a href="emailto:hello@pdu.pub">hello@pdu.pub</a>
sidebar-avatar: Wechat.png
