url: https://pdu.pub # the base hostname & protocol for your site, e.g. http://example.com
baseurl:  # the subpath of your site, e.g. /blog
title: ParaDigi Universe # the name of your site, e.g. ACME Corp.
logo: 
description: A P2P Social Networking Service.